#region License
// 
// Author: Joe McLain <nmp.developer@outlook.com>
// Copyright (c) 2015, Joe McLain and Digital Writing
// 
// Licensed under Eclipse Public License, Version 1.0 (EPL-1.0)
// See the file LICENSE.txt for details.
// 
#endregion
#region Generated
//
// This file was generated by a tool on 8/24/2015 2:40:51 PM an should not be 
// modified unless removed from the "Others" directory and added to
// a different collection of Tags
//
// Any modifications will be lost the next time the file is generated.
//
#endregion
using System;
using System.Collections.Generic;
using System.Linq;

namespace SharpHtml {

	/////////////////////////////////////////////////////////////////////////////

	public class Hr : Tag {
		protected override string _TagName => "hr";
		protected override TagRenderMode RenderMode => TagRenderMode.VoidTag;

		/////////////////////////////////////////////////////////////////////////////

		public Hr()
		{		
		}
	}

}